# typed: false
# frozen_string_literal: true

# AUTO-GENERATED by packages/cli/scripts/generate-homebrew-formula.mjs: do not edit manually.
# Regenerated on each v* release by supatype/.github/workflows/cli-release.yml and pushed here.

class Supatype < Formula
  desc "Type-first platform for PostgreSQL"
  homepage "https://supatype.com"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://releases.supatype.com/cli/v0.2.1/supatype-cli-darwin-arm64.tar.gz"
      sha256 "4007f5242d9dc727bc35c1ed3ab2a2065e659edcaa531c712221f80780d31106"
    end
    on_intel do
      url "https://releases.supatype.com/cli/v0.2.1/supatype-cli-darwin-amd64.tar.gz"
      sha256 "07bdb7530d3cad76799604a36bcb5aa6c949a635ca46ca41fc360090b066e8c2"
    end
  end

  on_linux do
    on_arm do
      url "https://releases.supatype.com/cli/v0.2.1/supatype-cli-linux-arm64.tar.gz"
      sha256 "afd1d91b38f3a15603fb9f53540f7404577da36637db0ff43b6073a02e57bc4a"
    end
    on_intel do
      url "https://releases.supatype.com/cli/v0.2.1/supatype-cli-linux-amd64.tar.gz"
      sha256 "f325d228401216a91e5a8ac17da7b1ae9e32a92fbd016195ff51eb85aae08bf6"
    end
  end

  def install
    bin.install "supatype"
  end

  def post_install
    system bin/"supatype", "_postinstall"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/supatype --version", 0)
  end
end
