# typed: false
# frozen_string_literal: true

# AUTO-GENERATED by packages/cli/scripts/generate-homebrew-formula.mjs: do not edit manually.
# Regenerated on each v* release by supatype/.github/workflows/cli-release.yml and pushed here.

class Supatype < Formula
  desc "Type-first platform for PostgreSQL"
  homepage "https://supatype.com"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://releases.supatype.com/cli/v0.2.0/supatype-cli-darwin-arm64.tar.gz"
      sha256 "bae34285fc0e0113d34c78499019c9082f6fa71c056b5423fb71fc607a277213"
    end
    on_intel do
      url "https://releases.supatype.com/cli/v0.2.0/supatype-cli-darwin-amd64.tar.gz"
      sha256 "ef6541556ed4dbb752917f119823ddbfce1641892a4fe1862a59f43a3f3747e2"
    end
  end

  on_linux do
    on_arm do
      url "https://releases.supatype.com/cli/v0.2.0/supatype-cli-linux-arm64.tar.gz"
      sha256 "8c1fbb3c25747c68f59e3ffbe8982c9ed1afdb83d0b51f61e781112628e3fac9"
    end
    on_intel do
      url "https://releases.supatype.com/cli/v0.2.0/supatype-cli-linux-amd64.tar.gz"
      sha256 "fda1810a7d4d6153fbe948ff17769e78e561c3f47b0fe4ffa5714076c4e1d25a"
    end
  end

  def install
    bin.install "supatype"
  end

  def post_install
    system bin/"supatype", "_postinstall"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/supatype --version", 0)
  end
end
