# typed: false
# frozen_string_literal: true

# AUTO-GENERATED by packages/cli/scripts/generate-homebrew-formula.mjs: do not edit manually.
# Regenerated on each v* release by supatype/.github/workflows/cli-release.yml and pushed here.

class Supatype < Formula
  desc "Type-first platform for PostgreSQL"
  homepage "https://supatype.com"
  version "0.1.9"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://releases.supatype.com/cli/v0.1.9/supatype-cli-darwin-arm64.tar.gz"
      sha256 "2e8d942432563bf029dfa7509661f86eef58f4fc5a9d8809e251a64abd2691b1"
    end
    on_intel do
      url "https://releases.supatype.com/cli/v0.1.9/supatype-cli-darwin-amd64.tar.gz"
      sha256 "4b39b0a75b121b20ebbf50e657321f2acd6a815dd6446c8b680cca3c1dcac5c3"
    end
  end

  on_linux do
    on_arm do
      url "https://releases.supatype.com/cli/v0.1.9/supatype-cli-linux-arm64.tar.gz"
      sha256 "bfa41fb3d29a0a6b55f94d96a01fef115368f64deaab1d8fef68cb397265a76e"
    end
    on_intel do
      url "https://releases.supatype.com/cli/v0.1.9/supatype-cli-linux-amd64.tar.gz"
      sha256 "e55a0cd1c24f0deb5039d358f5963d42e936258e8ba5325e7805eb5d2a6c64d2"
    end
  end

  def install
    bin.install "supatype"
  end

  def post_install
    system bin/"supatype", "_postinstall"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/supatype --version", 0)
  end
end
